name: Validate Commit Message

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate commits
        run: |
          git fetch origin main
          COMMITS=$(git log origin/main..HEAD --no-merges --pretty=format:"%s")
      
          echo "$COMMITS" | while IFS= read -r commit
          do
            echo "Checking: $commit"
      
            if [[ ! "$commit" =~ PNGW-[0-9]+ ]]; then
              if [[ ! "$commit" =~ PNGW-[0-9]+ ]]; then
                echo "❌ Error: Invalid commit message format."
                echo "👉 Commit: '$commit'"
                echo "💡 Message must contain a task ID like PNGW-123"
                exit 1
              fi
          done
